---
# Labels names are important as they are used by Release Drafter to decide
# regarding where to record them in changelog or if to skip them.
#
# The repository labels will be automatically configured using this file and
# the GitHub Action https://github.com/marketplace/actions/github-labeler.
## more info https://github.com/crazy-max/ghaction-github-labeler

# -------------------------------- Versioning -------------------------------- #
- name: major
  descripion: "Backwards incompatible changes"
  color: AB2232

- name: minor
  description: "Added backwards compatible functionality"
  color: 0A8844

- name: patch
  description: "Small changes and bug fixes"
  color: FBCA0C

# ----------------------------------- Core ----------------------------------- #
- name: backwards incompatible
  description: incompatible changes to how the application works
  color: AB2232

- name: bug
  description: Something isn't working
  color: d23832

- name: enhancement
  description: New feature or request
  color: 0A8844

# - name: help wanted
#   description: Extra attention is needed
#   color: 95FFA4

# - name: question
#   description: Further information is requested
#   color: EE328E

# ------------------------------- Improvements ------------------------------- #
# - name: performance
#   description: Improving efficiency and speed
#   color: "F2A33C"

- name: refactoring
  description: Refactoring
  color: FBCA0C

- name: documentation
  description: Improvements or additions to documentation
  color: F695C4

# -------------------------- Tooling and automation -------------------------- #
- name: build
  description: Compiling and packaging
  color: "962EDD"

- name: continuous integration
  description: Integration new code
  color: FCBFE3

- name: developer tools
  description: Developer tools and automation
  color: "A8D8F0"

- name: deployment
  description: Deploying the application
  color: E1BFFC

# ------------------------------- Dependencies ------------------------------- #
- name: dependencies
  description: Pull requests that update dependencies
  color: 0366d6

# ------------------------------ Utility labels ------------------------------ #
- name: automerge
  color: "ffffff"
  description: "Automerge this PR"

- name: "stale"
  color: "ffffff"
  description: ""
# - name: duplicate
#   description: This issue or pull request already exists
#   color: ffffff

# - name: invalid
#   description: This doesn't seem right
#   color: ffffff

# - name: wontfix
#   description: This will not be worked on
#   color: ffffff
