name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: ":boom: Breaking Changes"
    label: "breaking"

  - title: ":rocket: Features"
    label: "enhancement"

  - title: ":beetle: Fixes"
    label: "bug"

  - title: ":books: Documentation"
    label: "documentation"

  - title: ":hammer: Maintanance"
    labels:
      - "refactoring"
      - "continuous integration"
      - developer tools
      - deployment
      - build

  - title: ":package: Dependencies"
    labels:
      - "dependencies"

version-resolver:
  major:
    labels:
      - "major"
      - "backwards incompatible"

  minor:
    labels:
      - "minor"

  patch:
    labels:
      - "patch"

  default: patch

template: |
  $CHANGES
