group:
  repos: |
    emma-simbot/datasets
  files:
    - source: .github/
      dest: .github/
      deleteOrphaned: true
    - source: .vscode/
      dest: .vscode/
      deleteOrphaned: true
    - scripts/
    - .editorconfig
    - .env.example
    - .flake8
    - .gitattributes
    - .gitignore
    - .pre-commit-config.yaml
    - .rsync-filter
    - Makefile
    - CONTRIBUTING.md
    - pytest.ini
    - .mypy.ini
