name: Releases

on:
  push:
    branches:
      - main

jobs:
  draft_release:
    name: Draft a release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  labeler:
    name: Update labels
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.0.0
