name: Sync changes to downstream repos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    name: Sync files downstream
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.PAT }}
